version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - pip install aws-cdk-lib constructs
      - npm install -g aws-cdk                # ensure cdk CLI available
  build:
    commands:
      - cdk synth LambdaStack -v -o cdk.out
artifacts:
  files:
    - cdk.out/LambdaStack.template.json
