version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt

  build:
    commands:
      - cdk synth LambdaStack -o cdk.out

artifacts:
  base-directory: cdk.out
  files:
    - LambdaStack.template.json        # ✅ Required for CloudFormation deploy
    - assets/**/*                      # ✅ Includes Lambda packaged zip file
